config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :courses
  resources :students do
    resources :matriculas
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :matriculas, dependent: :destroy
  has_many :students, through: :matriculas

  validates :name, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :status, presence: true
end

app/models/matricula.rb
class Matricula < ActiveRecord::Base
  belongs_to :student
  belongs_to :course

  before_save :get_date

  def get_date
    self.entry_at = DateTime.now
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :matriculas, dependent: :destroy
  has_many :courses, through: :matriculas

  validates :name, presence: true, length: { minimum: 3 }
  validates :register_number, presence: true,length: { minimum: 2 }
  validates :status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :find_course, only: [:edit,:show,:update,:destroy]

  def index
    @courses = Course.all.order("name ASC")
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def show
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to @course, notice: "O Curso foi cadastrado com sucesso."
    else
      render 'new', notice: "Ocorreu um erro."
    end
  end

  def update
    if @course.update(course_params)
      redirect_to @course, notice: "O Curso foi atualizado com sucesso."
    else
      render 'edit', notice: "Ocorreu um erro."
    end
  end

  def destroy
    @course.destroy
    redirect_to courses_path
  end

  private
  def course_params
    params.require(:course).permit(:name, :description, :status)
  end

  def find_course
    @course = Course.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
  end
end

app/controllers/matriculas_controller.rb
class MatriculasController < ApplicationController

  def create
    @student = Student.find(params[:student_id])
    @matricula = Matricula.new
    @matricula.student_id = params[:student_id]
    @matricula.course_id = params[:matricula][:course_id]
    if @matricula.save
      @student.status = 1
      @student.update(status: 1)
      redirect_to @student, notice: "O Estudante foi matriculado com sucesso."
    else
      redirect_to root_path, notice: "Ocorreu um erro."
    end
  end

  def destroy
    @student = Student.find(params[:student_id])
    @matricula = Matricula.where(student_id: params[:student_id]).first
    if @matricula.destroy
      @student.update(status: 0)
      redirect_to @student, notice: "O Estudante foi desvinculado com sucesso."
    else
      redirect_to root_path, notice: "Ocorreu um erro."
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :find_student, only: [:edit,:show,:update,:destroy]

  def index
    @students = Student.all.order("name ASC")
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def show
    @matricula = Matricula.where(student_id: params[:id]).first
    if @matricula
      @course = Course.find(@matricula.course_id)
    end
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student, notice: "O Estudante foi cadastrado com sucesso."
    else
      render 'new', notice: "Ocorreu um erro."
    end
  end

  def update
    if @student.update(student_params)
      redirect_to @student, notice: "O Estudante foi atualizado com sucesso."
    else
      render 'edit',notice: "Ocorreu um erro."
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path
  end

  private
  def student_params
    params.require(:student).permit(:name, :register_number, :status)
  end

  def find_student
    @student = Student.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @student_count = Student.count
    @course_count = Course.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/courses/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
      <%= form_for @course do |f|%>

        <% if @course.errors.any? %>
            <h2><%= pluralize(@course.errors.count, " erro") %> encontrado(s): </h2>
            <ul>
              <% @course.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
        <% end %>
        <div class="form-group">
          <%= f.label :name, 'Nome'%>
          <%= f.text_field :name, class: 'form-control'%></br>
        </div>

        <div class="form-group">
          <%= f.label :description, 'Descrição'%>
          <%= f.text_area :description, class: 'form-control'%></br>
        </div>

        <div class="form-group">
          <%= f.check_box :status %>
        	<%= f.label :status, "Disponibilizar Curso? "%>
        </div>

        <%= f.submit class:'btn btn-default'%>
      <% end %>

    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h3 class="text-center">ALTERAR CURSO</h3>
  </div>
</div>
<%= render 'form'%>

app/views/courses/index.html.erb
<div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h3>Lista dos Cursos</h3>
          <br/>
          <% if @courses.empty? %>
            <h3>Nenhum Curso cadastrado! </h3>
          <% else %>
          	<table class="table table-striped">
	          	<tr>
      					<th>Id</th>
      					<th>Nome</th>
      					<th>Ativo?</th>
                <th></th>
                <th></th>
                <th></th>
      				</tr>
	            <% @courses.each do |course| %>
	            <tr>
      					<td><%= course.id %></td>
      					<td><%= link_to course.name, course %></td>
      					<td>
      						<% if course.status == 1 %>
      							<%= 'Sim' %>
      						<% else %>
      							<%= 'Não' %>
      						<% end %>
      					</td>
                <td>
                  <%= link_to course do%>
                    <i class="fa fa-search"></i>
                  <%end%>
                </td>
                <td>
                  <%= link_to edit_course_path(course) do%>
                    <i class="fa fa-pencil"></i>
                  <%end%>
                </td>
                <td>
                  <%= link_to course , method: :delete, data: {confirm: "Are you sure?"} do%>
                    <i class="fa fa-times"></i>
                  <%end%>
                </td>
      				</tr>
	            <% end %>
            </table>
            <br>
            <br>
          <% end %>
        </div>
      </div>
    </div> <!-- /container -->

app/views/courses/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h3 class="text-center">NOVO CURSO</h3>
  </div>
</div>
<%= render 'form'%>

app/views/courses/show.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h4 class="text-center">INFORMAÇÕES DO CURSO</h4><br/>
    <strong>Curso Id: </strong><%= @course.id%><br/>
    <strong>Nome: </strong><%= @course.name%><br/>
    <strong>Descrição: </strong><%= @course.description%><br/>
    <strong>Status: </strong>
      <% if @course.status == 1 %>
        <%= 'Ativo' %>
      <% else %>
        <%= 'Não Ativo' %>
      <% end %><br/>
    <strong>Criado em: </strong><%= @course.created_at.strftime("%d/%m/%Y às %H:%M ")%>

    <br/><br/><br/>

    <div class="row">
      <div class="col-md-4 col-md-offset-2">
         <%= link_to 'Alterar', edit_course_path(@course), class: "btn btn-default btn-block" %>
      </div>
      <div class="col-md-4">
        <%= link_to 'Excluir', course_path, class: "btn btn-danger btn-block",
                                  method: :delete, data: {confirm: "Are you sure?"} %>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProficiencyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='//fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <%= link_to "UNIVERSITY", root_path, class:'navbar-brand'%>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Estudantes", students_path%></li>
          <li><%= link_to "Cursos", courses_path%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
            aria-haspopup="true" aria-expanded="false">Cadastros <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Novo Estudante", new_student_path%></li>
              <li><%= link_to "Novo Curso", new_course_path%></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% elsif alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>
  </div>

  <%= yield %>

</body>
</html>

app/views/matriculas/_form.html.erb
<br/><br/>
<div class="well">
  <div class="form-inline">
    <%= simple_form_for([@student, @student.matriculas.build]) do |f|%>
      <%= f.label :course_id, 'Curso: ' %>
      <%= f.collection_select :course_id, Course.where(status: 1).order("name ASC"), :id, :name, {prompt: false}, {class: "form-control"} %>
      <%= f.submit 'Realizar Matricula', class: 'btn btn-default'%>
    <% end %>
  </div>
</div>

app/views/students/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
      <%= form_for @student do |f|%>

        <% if @student.errors.any? %>
            <h2><%= pluralize(@student.errors.count, " erro") %> encontrado(s): </h2>
            <ul>
              <% @student.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
        <% end %>
        <div class="form-group">
          <%= f.label :name, 'Nome'%>
          <%= f.text_field :name, class: 'form-control'%></br>
        </div>

        <div class="form-group">
          <%= f.label :register_number, 'Numero de Matricula'%>
          <%= f.text_field :register_number, class: 'form-control'%></br>
        </div>

        <%= f.submit class:'btn btn-default'%>
      <% end %>

    </div>
  </div>
</div>

app/views/students/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h3 class="text-center">ALTERAR ESTUDANTE</h3>
  </div>
</div>
<%= render 'form'%>

app/views/students/index.html.erb
<div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h3>Lista dos Estudantes</h3>
          <br/>
          <% if @students.empty? %>
            <h3>Nenhum Estudante cadastrado! </h3>
          <% else %>
          	<table class="table table-striped">
	          	<tr>
      					<th>Id</th>
      					<th>Nome</th>
      					<th>Matriculado?</th>
                <th></th>
                <th></th>
                <th></th>
      				</tr>
	            <% @students.each do |student| %>
  	            <tr>
        					<td><%= student.id %></td>
        					<td><%= link_to student.name, student %></td>
        					<td>
        						<% if student.status == 1 %>
        							<%= 'Sim' %>
        						<% else %>
        							<%= 'Não' %>
        						<% end %>
        					</td>
                  <td>
                    <%= link_to student do%>
                      <i class="fa fa-search"></i>
                    <%end%>
                  </td>
                  <td>
                    <%= link_to edit_student_path(student) do%>
                      <i class="fa fa-pencil"></i>
                    <%end%>
                  </td>
                  <td>
                    <%= link_to student , method: :delete, data: {confirm: "Are you sure?"} do%>
                      <i class="fa fa-times"></i>
                    <%end%>
                  </td>
        				</tr>
	            <% end %>
            </table>
            <br>
            <br>
          <% end %>
        </div>
      </div>
    </div> <!-- /container -->

app/views/students/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h3 class="text-center">NOVO ESTUDANTE</h3>
  </div>
</div>
<%= render 'form'%>

app/views/students/show.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h4 class="text-center">INFORMAÇÕES DO ESTUDANTE</h4><br/>
    <strong>Estudante Id: </strong><%= @student.id%><br/>
    <strong>Nome: </strong><%= @student.name%><br/>
    <strong>Numero de Registro: </strong><%= @student.register_number%><br/>
    <strong>Cadastrado em: </strong><%= @student.created_at.strftime("%d/%m/%Y às %H:%M ")%></br>
    <strong>Status: </strong>
      <% if @student.status == 1 %>
        Matriculado em <%= @course.name %> em <%= @matricula.entry_at.strftime("%d/%m/%Y às %H:%M ")%>
      <% else %>
        <%= 'Não Matriculado' %>
        <%= render 'matriculas/form'%>
      <% end %><br/>
    <br/>
    <div class="row">
      <div class="col-md-4 ">
         <%= link_to 'Alterar', edit_student_path(@student), class: "btn btn-default btn-block" %>
      </div>
      <% if @student.status == 1 %>
        <div class="col-md-4 ">
           <%= link_to 'Desvincular', student_matricula_path(:student_id => @student.id), class: "btn btn-danger btn-block",
                                     method: :delete, data: {confirm: "Tem certeza que quer desvincular?"} %>
        </div>
      <% end %>
      <div class="col-md-4">
        <%= link_to 'Excluir', student_path, class: "btn btn-danger btn-block",
                                  method: :delete, data: {confirm: "Tem certeza que quer Exluir?"} %>
      </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row centered-form center-block">
    <%= link_to students_path do%>
      <div class="col-md-3 col-md-offset-3 estudante comum">
        <p>Estudantes: <%= @student_count%><p>
      </div>
    <% end %>
    <%= link_to courses_path do%>
      <div class="col-md-3 curso comum">
        <p>Cursos: <%= @course_count%><p>
      </div>
    <% end %>
  </div>
</div>